language: ruby
bundler_args: --without debug extra redis kyoto
script: bundle exec rake test_with_coveralls
sudo: false
cache: bundler
rvm:
  - 2.2
  - 2.1
  - 2
  - rbx-2
matrix:
  allow_failures:
    - rvm: rbx-2
notifications:
  email:
    - sylvester@keil.or.at
  on_success: change
  on_failure: always
